name: Lint

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci --no-audit

      - name: Lerna bootstrap
        run: npx lerna bootstrap --force-local --since=$(git merge-base --fork-point origin/dev)

      - name: Lint
        run: npm run lint
